// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (name, token_hash, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, token_hash, created_at, last_used_at, created_by
`

type CreateApiTokenParams struct {
	Name      string
	TokenHash string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createApiToken, arg.Name, arg.TokenHash, arg.CreatedBy)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteApiToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiToken, id)
	return err
}

const getApiToken = `-- name: GetApiToken :one
SELECT id, name, token_hash, created_at, last_used_at, created_by FROM api_tokens WHERE id = $1
`

func (q *Queries) GetApiToken(ctx context.Context, id pgtype.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getApiTokenByHashWithOwner = `-- name: GetApiTokenByHashWithOwner :one
SELECT
    api_tokens.id, api_tokens.created_by,
    users.role AS owner_role, users.disabled AS owner_disabled
FROM api_tokens
LEFT JOIN users ON users.id = api_tokens.created_by
WHERE api_tokens.token_hash = $1
`

type GetApiTokenByHashWithOwnerRow struct {
	ID            pgtype.UUID
	CreatedBy     pgtype.UUID
	OwnerRole     NullUserRole
	OwnerDisabled pgtype.Bool
}

func (q *Queries) GetApiTokenByHashWithOwner(ctx context.Context, tokenHash string) (GetApiTokenByHashWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getApiTokenByHashWithOwner, tokenHash)
	var i GetApiTokenByHashWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OwnerRole,
		&i.OwnerDisabled,
	)
	return i, err
}

const listApiTokensForOwner = `-- name: ListApiTokensForOwner :many
SELECT api_tokens.id, api_tokens.name, api_tokens.token_hash, api_tokens.created_at, api_tokens.last_used_at, api_tokens.created_by, users.username AS owner_username
FROM api_tokens
LEFT JOIN users ON users.id = api_tokens.created_by
WHERE api_tokens.created_by = $1
ORDER BY api_tokens.created_at
`

type ListApiTokensForOwnerRow struct {
	ID            pgtype.UUID
	Name          string
	TokenHash     string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	OwnerUsername pgtype.Text
}

func (q *Queries) ListApiTokensForOwner(ctx context.Context, createdBy pgtype.UUID) ([]ListApiTokensForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listApiTokensForOwner, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensForOwnerRow
	for rows.Next() {
		var i ListApiTokensForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiTokensWithOwner = `-- name: ListApiTokensWithOwner :many
SELECT api_tokens.id, api_tokens.name, api_tokens.token_hash, api_tokens.created_at, api_tokens.last_used_at, api_tokens.created_by, users.username AS owner_username
FROM api_tokens
LEFT JOIN users ON users.id = api_tokens.created_by
ORDER BY api_tokens.created_at
`

type ListApiTokensWithOwnerRow struct {
	ID            pgtype.UUID
	Name          string
	TokenHash     string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	OwnerUsername pgtype.Text
}

func (q *Queries) ListApiTokensWithOwner(ctx context.Context) ([]ListApiTokensWithOwnerRow, error) {
	rows, err := q.db.Query(ctx, listApiTokensWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensWithOwnerRow
	for rows.Next() {
		var i ListApiTokensWithOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiTokenLastUsed = `-- name: TouchApiTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchApiTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchApiTokenLastUsed, id)
	return err
}
