// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (name, token_hash)
VALUES ($1, $2)
RETURNING id, name, token_hash, created_at, last_used_at
`

type CreateApiTokenParams struct {
	Name      string
	TokenHash string
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createApiToken, arg.Name, arg.TokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteApiToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiToken, id)
	return err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT id, name, token_hash, created_at, last_used_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getApiTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listApiTokens = `-- name: ListApiTokens :many
SELECT id, name, token_hash, created_at, last_used_at FROM api_tokens ORDER BY created_at
`

func (q *Queries) ListApiTokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listApiTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiTokenLastUsed = `-- name: TouchApiTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchApiTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchApiTokenLastUsed, id)
	return err
}
