// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, access_token_hash)
VALUES ($1, $2)
RETURNING id, name, access_token_hash, created_at, last_seen_at
`

type CreateClientParams struct {
	Name            string
	AccessTokenHash string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Name, arg.AccessTokenHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, access_token_hash, created_at, last_seen_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getClientByTokenHash = `-- name: GetClientByTokenHash :one
SELECT id, name, access_token_hash, created_at, last_seen_at FROM clients WHERE access_token_hash = $1
`

func (q *Queries) GetClientByTokenHash(ctx context.Context, accessTokenHash string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByTokenHash, accessTokenHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, access_token_hash, created_at, last_seen_at FROM clients ORDER BY created_at
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessTokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameClient = `-- name: RenameClient :one
UPDATE clients SET name = $2 WHERE id = $1 RETURNING id, name, access_token_hash, created_at, last_seen_at
`

type RenameClientParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameClient(ctx context.Context, arg RenameClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, renameClient, arg.ID, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchClientLastSeen = `-- name: TouchClientLastSeen :exec
UPDATE clients SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchClientLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchClientLastSeen, id)
	return err
}
