// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, access_token_hash, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, access_token_hash, created_at, last_seen_at, created_by
`

type CreateClientParams struct {
	Name            string
	AccessTokenHash string
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Name, arg.AccessTokenHash, arg.CreatedBy)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, access_token_hash, created_at, last_seen_at, created_by FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CreatedBy,
	)
	return i, err
}

const getClientByTokenHash = `-- name: GetClientByTokenHash :one
SELECT id, name, access_token_hash, created_at, last_seen_at, created_by FROM clients WHERE access_token_hash = $1
`

func (q *Queries) GetClientByTokenHash(ctx context.Context, accessTokenHash string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByTokenHash, accessTokenHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CreatedBy,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, access_token_hash, created_at, last_seen_at, created_by FROM clients ORDER BY created_at
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessTokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsForOwner = `-- name: ListClientsForOwner :many
SELECT clients.id, clients.name, clients.access_token_hash, clients.created_at, clients.last_seen_at, clients.created_by, users.username AS owner_username
FROM clients
LEFT JOIN users ON users.id = clients.created_by
WHERE clients.created_by = $1
ORDER BY clients.created_at
`

type ListClientsForOwnerRow struct {
	ID              pgtype.UUID
	Name            string
	AccessTokenHash string
	CreatedAt       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	OwnerUsername   pgtype.Text
}

func (q *Queries) ListClientsForOwner(ctx context.Context, createdBy pgtype.UUID) ([]ListClientsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listClientsForOwner, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsForOwnerRow
	for rows.Next() {
		var i ListClientsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessTokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.CreatedBy,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsWithOwner = `-- name: ListClientsWithOwner :many
SELECT clients.id, clients.name, clients.access_token_hash, clients.created_at, clients.last_seen_at, clients.created_by, users.username AS owner_username
FROM clients
LEFT JOIN users ON users.id = clients.created_by
ORDER BY clients.created_at
`

type ListClientsWithOwnerRow struct {
	ID              pgtype.UUID
	Name            string
	AccessTokenHash string
	CreatedAt       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	OwnerUsername   pgtype.Text
}

func (q *Queries) ListClientsWithOwner(ctx context.Context) ([]ListClientsWithOwnerRow, error) {
	rows, err := q.db.Query(ctx, listClientsWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsWithOwnerRow
	for rows.Next() {
		var i ListClientsWithOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessTokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.CreatedBy,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameClient = `-- name: RenameClient :one
UPDATE clients SET name = $2 WHERE id = $1 RETURNING id, name, access_token_hash, created_at, last_seen_at, created_by
`

type RenameClientParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameClient(ctx context.Context, arg RenameClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, renameClient, arg.ID, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessTokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CreatedBy,
	)
	return i, err
}

const touchClientLastSeen = `-- name: TouchClientLastSeen :exec
UPDATE clients SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchClientLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchClientLastSeen, id)
	return err
}
