// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessagesByIDs = `-- name: GetMessagesByIDs :many
SELECT id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at FROM messages WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetMessagesByIDs(ctx context.Context, ids []pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.PhoneNumber,
			&i.Content,
			&i.ClientID,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.DispatchedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByIDsForOwner = `-- name: GetMessagesByIDsForOwner :many
SELECT messages.id, messages.batch_id, messages.phone_number, messages.content, messages.client_id, messages.status, messages.error, messages.received_at, messages.dispatched_at, messages.sent_at FROM messages
JOIN clients ON clients.id = messages.client_id
WHERE messages.id = ANY($1::uuid[])
  AND clients.created_by = $2
`

type GetMessagesByIDsForOwnerParams struct {
	Ids   []pgtype.UUID
	Owner pgtype.UUID
}

func (q *Queries) GetMessagesByIDsForOwner(ctx context.Context, arg GetMessagesByIDsForOwnerParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByIDsForOwner, arg.Ids, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.PhoneNumber,
			&i.Content,
			&i.ClientID,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.DispatchedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (batch_id, phone_number, content, client_id)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at
`

type InsertMessageParams struct {
	BatchID     pgtype.UUID
	PhoneNumber string
	Content     string
	ClientID    pgtype.UUID
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.BatchID,
		arg.PhoneNumber,
		arg.Content,
		arg.ClientID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.PhoneNumber,
		&i.Content,
		&i.ClientID,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.DispatchedAt,
		&i.SentAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at FROM messages
WHERE ($1::message_status IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR client_id = $2)
  AND ($3::uuid IS NULL OR batch_id = $3)
ORDER BY received_at DESC
LIMIT $4
`

type ListMessagesParams struct {
	Status   NullMessageStatus
	ClientID pgtype.UUID
	BatchID  pgtype.UUID
	Lim      int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.Status,
		arg.ClientID,
		arg.BatchID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.PhoneNumber,
			&i.Content,
			&i.ClientID,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.DispatchedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForOwner = `-- name: ListMessagesForOwner :many
SELECT messages.id, messages.batch_id, messages.phone_number, messages.content, messages.client_id, messages.status, messages.error, messages.received_at, messages.dispatched_at, messages.sent_at FROM messages
JOIN clients ON clients.id = messages.client_id
WHERE clients.created_by = $1
  AND ($2::message_status IS NULL OR messages.status = $2)
  AND ($3::uuid IS NULL OR messages.client_id = $3)
  AND ($4::uuid IS NULL OR messages.batch_id = $4)
ORDER BY messages.received_at DESC
LIMIT $5
`

type ListMessagesForOwnerParams struct {
	Owner    pgtype.UUID
	Status   NullMessageStatus
	ClientID pgtype.UUID
	BatchID  pgtype.UUID
	Lim      int32
}

func (q *Queries) ListMessagesForOwner(ctx context.Context, arg ListMessagesForOwnerParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesForOwner,
		arg.Owner,
		arg.Status,
		arg.ClientID,
		arg.BatchID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.PhoneNumber,
			&i.Content,
			&i.ClientID,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.DispatchedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForClient = `-- name: ListPendingForClient :many
SELECT id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at FROM messages
WHERE client_id = $1 AND status = 'pending'
ORDER BY received_at
`

func (q *Queries) ListPendingForClient(ctx context.Context, clientID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listPendingForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.PhoneNumber,
			&i.Content,
			&i.ClientID,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.DispatchedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDispatched = `-- name: MarkDispatched :execrows
UPDATE messages
SET status = 'dispatched', dispatched_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkDispatched(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDispatched, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFailed = `-- name: MarkFailed :one
UPDATE messages
SET status = 'failed', error = $2
WHERE id = $1
RETURNING id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at
`

type MarkFailedParams struct {
	ID    pgtype.UUID
	Error string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (Message, error) {
	row := q.db.QueryRow(ctx, markFailed, arg.ID, arg.Error)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.PhoneNumber,
		&i.Content,
		&i.ClientID,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.DispatchedAt,
		&i.SentAt,
	)
	return i, err
}

const markSent = `-- name: MarkSent :one
UPDATE messages
SET status = 'sent', sent_at = $2, error = ''
WHERE id = $1
RETURNING id, batch_id, phone_number, content, client_id, status, error, received_at, dispatched_at, sent_at
`

type MarkSentParams struct {
	ID     pgtype.UUID
	SentAt pgtype.Timestamptz
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) (Message, error) {
	row := q.db.QueryRow(ctx, markSent, arg.ID, arg.SentAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.PhoneNumber,
		&i.Content,
		&i.ClientID,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.DispatchedAt,
		&i.SentAt,
	)
	return i, err
}
