// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	DeleteApiToken(ctx context.Context, id pgtype.UUID) error
	DeleteClient(ctx context.Context, id pgtype.UUID) error
	GetApiTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetClient(ctx context.Context, id pgtype.UUID) (Client, error)
	GetClientByTokenHash(ctx context.Context, accessTokenHash string) (Client, error)
	GetSettings(ctx context.Context) (GetSettingsRow, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListApiTokens(ctx context.Context) ([]ApiToken, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListPendingForClient(ctx context.Context, clientID pgtype.UUID) ([]Message, error)
	MarkDispatched(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkFailed(ctx context.Context, arg MarkFailedParams) (Message, error)
	MarkSent(ctx context.Context, arg MarkSentParams) (Message, error)
	RenameClient(ctx context.Context, arg RenameClientParams) (Client, error)
	TouchApiTokenLastUsed(ctx context.Context, id pgtype.UUID) error
	TouchClientLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (UpdateSettingsRow, error)
}

var _ Querier = (*Queries)(nil)
