// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, last_used_at, expires_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, tokenHash)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT
    sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at,
    sessions.last_used_at, sessions.expires_at,
    users.username AS username, users.role AS role, users.disabled AS disabled
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
`

type GetSessionByHashRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Username   string
	Role       UserRole
	Disabled   bool
}

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Username,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.last_used_at,
    users.username AS username
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.expires_at > now()
ORDER BY sessions.last_used_at DESC
`

type ListSessionsRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	Username   string
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
