// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT delay_ms, jitter_ms FROM settings WHERE id = 1
`

type GetSettingsRow struct {
	DelayMs  int32
	JitterMs int32
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(&i.DelayMs, &i.JitterMs)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings SET delay_ms = $1, jitter_ms = $2 WHERE id = 1
RETURNING delay_ms, jitter_ms
`

type UpdateSettingsParams struct {
	DelayMs  int32
	JitterMs int32
}

type UpdateSettingsRow struct {
	DelayMs  int32
	JitterMs int32
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (UpdateSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.DelayMs, arg.JitterMs)
	var i UpdateSettingsRow
	err := row.Scan(&i.DelayMs, &i.JitterMs)
	return i, err
}
