// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: porukator/v1/porukator.proto
//
package porukator.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface

/**
 *  ClientService is the device API for the Android app. All RPCs require the
 *  device's access token as a bearer token; the device identity is derived from
 *  the token, never from request fields.
 */
public interface ClientServiceClientInterface {
  /**
   *  StreamJobs opens a server stream the service pushes SMS jobs onto. The
   *  device is marked online for the life of the stream. On connect the service
   *  first drains any jobs left pending while the device was offline.
   */
  public suspend fun streamJobs(headers: Headers = emptyMap()): ServerOnlyStreamInterface<Porukator.StreamJobsRequest, Porukator.Job>

  /**
   *  ReportDelivery records the outcome of one send. The device calls this after
   *  each SMS, success or failure.
   */
  public suspend fun reportDelivery(request: Porukator.ReportDeliveryRequest, headers: Headers = emptyMap()): ResponseMessage<Porukator.ReportDeliveryResponse>
}
