// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: porukator/v1/porukator.proto
//
package porukator.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface
import com.connectrpc.StreamType

/**
 *  ClientService is the device API for the Android app. All RPCs require the
 *  device's access token as a bearer token; the device identity is derived from
 *  the token, never from request fields.
 */
public class ClientServiceClient(
  private val client: ProtocolClientInterface,
) : ClientServiceClientInterface {
  /**
   *  StreamJobs opens a server stream the service pushes SMS jobs onto. The
   *  device is marked online for the life of the stream. On connect the service
   *  first drains any jobs left pending while the device was offline.
   */
  override suspend fun streamJobs(headers: Headers): ServerOnlyStreamInterface<Porukator.StreamJobsRequest, Porukator.Job> = client.serverStream(
    headers,
    MethodSpec(
    "porukator.v1.ClientService/StreamJobs",
      porukator.v1.Porukator.StreamJobsRequest::class,
      porukator.v1.Porukator.Job::class,
      StreamType.SERVER,
    ),
  )


  /**
   *  ReportDelivery records the outcome of one send. The device calls this after
   *  each SMS, success or failure.
   */
  override suspend fun reportDelivery(request: Porukator.ReportDeliveryRequest, headers: Headers): ResponseMessage<Porukator.ReportDeliveryResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "porukator.v1.ClientService/ReportDelivery",
      porukator.v1.Porukator.ReportDeliveryRequest::class,
      porukator.v1.Porukator.ReportDeliveryResponse::class,
      StreamType.UNARY,
    ),
  )

}
